apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  REACT_APP_API_BASE_URL: "https://matrix-meetings-bot.{{- .Values.settings.hostname -}}"
  REACT_APP_HOME_SERVER_URL: "https://synapse.{{- .Values.settings.hostname -}}"
